Delete command used instead of Create command
Error: Cannot create repo : /bin/pulp-admin rpm repo create blah", details: Execution of '/bin/pulp-admin  repo delete --bg --repo-id